version: "3.7"

services:

  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:5050"

  dbt:
    container_name: dbt
    build: dbt/.
    image: dbt-dev
    env_file:
      - ./.env
    volumes:
      - ./dbt/dbt_project:/home/dbt_project
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
